import type{Phase,Routine,WorkoutState}from'./types';
const now=()=>new Date().toISOString();
const blockAt=(r:Routine,i:number)=>r.blocks[i];
const exerciseAt=(r:Routine,s:WorkoutState)=>blockAt(r,s.blockIndex)?.exercises[s.exerciseIndex];
const phaseDuration=(r:Routine,s:WorkoutState,p:Phase)=>{const b=blockAt(r,s.blockIndex);if(!b)return 0;if(p==='EXERCISE'){const e=exerciseAt(r,s);return e?.mode==='time'?e.duration:0}if(p==='REST_BETWEEN_EXERCISES')return b.restBetweenExercises;if(p==='REST_BETWEEN_ROUNDS')return b.restBetweenRounds;if(p==='REST_BETWEEN_BLOCKS')return b.restAfterBlock;return 0};
const firstPopulatedBlock=(r:Routine,from=0)=>r.blocks.findIndex((b,i)=>i>=from&&b.exercises.length>0);
export const initialWorkout=(autoAdvance=true,routine?:Routine):WorkoutState=>{const b=routine?firstPopulatedBlock(routine):0;return{phase:routine&&b<0?'COMPLETED':'PREPARING',blockIndex:Math.max(0,b),roundIndex:0,exerciseIndex:0,remaining:5,elapsed:0,autoAdvance,completedExercises:0,startedAt:now(),lastTickAt:now()}};
const withDuration=(r:Routine,s:WorkoutState,p:Phase):WorkoutState=>({...s,phase:p,remaining:phaseDuration(r,s,p),lastTickAt:now()});
export function nextState(r:Routine,s:WorkoutState):WorkoutState{const b=blockAt(r,s.blockIndex);if(!b||!b.exercises.length){const ni=firstPopulatedBlock(r,s.blockIndex+1);return ni<0?{...s,phase:'COMPLETED',remaining:0,lastTickAt:now()}:withDuration(r,{...s,blockIndex:ni,roundIndex:0,exerciseIndex:0},'EXERCISE')}if(s.phase==='PREPARING')return withDuration(r,s,'EXERCISE');if(s.phase==='EXERCISE'){const completed=s.completedExercises+1;if(s.exerciseIndex<b.exercises.length-1)return withDuration(r,{...s,completedExercises:completed},'REST_BETWEEN_EXERCISES');if(s.roundIndex<b.rounds-1)return withDuration(r,{...s,completedExercises:completed},'REST_BETWEEN_ROUNDS');const nb=firstPopulatedBlock(r,s.blockIndex+1);if(nb>=0)return withDuration(r,{...s,completedExercises:completed},'REST_BETWEEN_BLOCKS');return{...s,phase:'COMPLETED',remaining:0,completedExercises:completed,lastTickAt:now()}}if(s.phase==='REST_BETWEEN_EXERCISES')return withDuration(r,{...s,exerciseIndex:s.exerciseIndex+1},'EXERCISE');if(s.phase==='REST_BETWEEN_ROUNDS')return withDuration(r,{...s,roundIndex:s.roundIndex+1,exerciseIndex:0},'EXERCISE');if(s.phase==='REST_BETWEEN_BLOCKS'){const ni=firstPopulatedBlock(r,s.blockIndex+1);return ni<0?{...s,phase:'COMPLETED',remaining:0}:withDuration(r,{...s,blockIndex:ni,roundIndex:0,exerciseIndex:0},'EXERCISE')}if(s.phase==='WAITING_FOR_MANUAL_CONTINUE')return nextState(r,{...s,phase:s.previousPhase??'EXERCISE'});return s}
export function tick(r:Routine,s:WorkoutState):WorkoutState{if(['PAUSED','WAITING_FOR_MANUAL_CONTINUE','COMPLETED'].includes(s.phase))return{...s,lastTickAt:now()};const e=exerciseAt(r,s);if(s.phase==='EXERCISE'&&e?.mode!=='time')return{...s,remaining:0,elapsed:s.elapsed+1,lastTickAt:now()};const n={...s,remaining:Math.max(0,s.remaining-1),elapsed:s.elapsed+1,lastTickAt:now()};if(n.remaining>0)return n;if(!s.autoAdvance)return{...n,phase:'WAITING_FOR_MANUAL_CONTINUE',previousPhase:s.phase};return nextState(r,n)}
export const completeCurrent=(r:Routine,s:WorkoutState)=>nextState(r,s.phase==='WAITING_FOR_MANUAL_CONTINUE'?{...s,phase:s.previousPhase??'EXERCISE'}:s);
export const skipCurrent=(r:Routine,s:WorkoutState)=>nextState(r,s);
export function previousState(r:Routine,s:WorkoutState):WorkoutState{if(s.exerciseIndex>0)return withDuration(r,{...s,exerciseIndex:s.exerciseIndex-1},'EXERCISE');if(s.roundIndex>0){const b=blockAt(r,s.blockIndex);return withDuration(r,{...s,roundIndex:s.roundIndex-1,exerciseIndex:Math.max(0,b.exercises.length-1)},'EXERCISE')}for(let i=s.blockIndex-1;i>=0;i--)if(r.blocks[i].exercises.length)return withDuration(r,{...s,blockIndex:i,roundIndex:Math.max(0,r.blocks[i].rounds-1),exerciseIndex:r.blocks[i].exercises.length-1},'EXERCISE');return withDuration(r,{...s,blockIndex:0,roundIndex:0,exerciseIndex:0},'EXERCISE')}
export const togglePause=(s:WorkoutState):WorkoutState=>s.phase==='PAUSED'?{...s,phase:s.previousPhase??'EXERCISE',lastTickAt:now()}:{...s,previousPhase:s.phase,phase:'PAUSED',lastTickAt:now()};
export function reconcileElapsed(r:Routine,s:WorkoutState,at=Date.now()){if(['PAUSED','WAITING_FOR_MANUAL_CONTINUE','COMPLETED'].includes(s.phase))return{...s,lastTickAt:new Date(at).toISOString()};let n=s;const seconds=Math.max(0,Math.min(3600,Math.floor((at-new Date(s.lastTickAt).getTime())/1000)));for(let i=0;i<seconds&&!['COMPLETED','WAITING_FOR_MANUAL_CONTINUE'].includes(n.phase);i++)n=tick(r,n);return{...n,lastTickAt:new Date(at).toISOString()}}
